// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MunicipalityChatbot.Infrastructure.Db;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MunicipalityChatbot.Infrastructure.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260131000000_AddCrawledPages")]
    partial class AddCrawledPages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MunicipalityChatbot.Domain.Entities.ApiCallAudit", b =>
                {
                    b.Property<Guid>("ApiCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("api_call_id");

                    b.Property<Guid>("ApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("RequestSummaryJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_summary_json");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("ResponseSummaryJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_summary_json");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("ApiCallId");

                    b.ToTable("api_calls", (string)null);
                });

            modelBuilder.Entity("MunicipalityChatbot.Domain.Entities.ApiDefinition", b =>
                {
                    b.Property<Guid>("ApiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("api_id");

                    b.Property<bool>("AllowInChat")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_in_chat");

                    b.Property<string>("AllowlistedDomain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("allowlisted_domain");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("api_name");

                    b.Property<string>("AuthConfigJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_config_json");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("auth_type");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("base_url");

                    b.Property<string>("BodySchemaJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_schema_json");

                    b.Property<string>("BodyTemplateJson")
                        .HasColumnType("text")
                        .HasColumnName("body_template_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HeadersTemplateJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers_template_json");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("method");

                    b.Property<string>("PathTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("path_template");

                    b.Property<string>("QueryParamsSchemaJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_params_schema_json");

                    b.Property<string>("ResponseHandlingNotes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_handling_notes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ApiId");

                    b.HasIndex("AllowInChat");

                    b.ToTable("api_definitions", (string)null);
                });

            modelBuilder.Entity("MunicipalityChatbot.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("MessageId");

                    b.HasIndex("SessionId");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("MunicipalityChatbot.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("UserLang")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("user_lang");

                    b.Property<string>("WidgetOrigin")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("widget_origin");

                    b.HasKey("SessionId");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("MunicipalityChatbot.Domain.Entities.CrawledPage", b =>
                {
                    b.Property<Guid>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_count");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastCrawledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_crawled_at");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url");

                    b.HasKey("PageId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("crawled_pages", (string)null);
                });

            modelBuilder.Entity("MunicipalityChatbot.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("doc_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectedLanguage")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("detected_language");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("filetype");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("filename");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("DocId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("MunicipalityChatbot.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocId")
                        .HasColumnType("uuid")
                        .HasColumnName("doc_id");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("filetype");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("filename");

                    b.Property<string>("Language")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<string>("SheetName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sheet_name");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("ChunkId");

                    b.HasIndex("DocId");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("MunicipalityChatbot.Domain.Entities.EmployeeUser", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("username");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("MunicipalityChatbot.Domain.Entities.Faq", b =>
                {
                    b.Property<Guid>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("faq_id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("department");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("TagsCsv")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("tags_csv");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FaqId");

                    b.HasIndex("Language", "IsActive");

                    b.ToTable("faqs", (string)null);
                });

            modelBuilder.Entity("MunicipalityChatbot.Domain.Entities.RoutingDecision", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("PlannerJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("planner_json");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("route");

                    b.Property<Guid?>("SelectedApiId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_api_id");

                    b.Property<string>("SelectedChunkIdsCsv")
                        .HasColumnType("text")
                        .HasColumnName("selected_chunk_ids_csv");

                    b.Property<Guid?>("SelectedFaqId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_faq_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("DecisionId");

                    b.HasIndex("Route");

                    b.ToTable("routing_decisions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
